# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/jwilm/alacritty



window:
        dimensions:
                columns: 80
                lines: 24


        padding:
                x: 10
                y: 10

        dynamic_padding: true

        decorations: none
font:

        size: 8.0

        normal:
                family: Hack
                style: Regular

colors:
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'
  cursor:
    text: '0x2E3440'
    cursor: '0xD8DEE9'
  normal:
    black: '0x3B4252'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x88C0D0'
    white: '0xE5E9F0'
  bright:
    black: '0x4C566A'
    red: '0xBF616A'
    green: '0xA3BE8C'
    yellow: '0xEBCB8B'
    blue: '0x81A1C1'
    magenta: '0xB48EAD'
    cyan: '0x8FBCBB'
    white: '0xECEFF4'


    background_opacity: 0.9
